version: '3.8'

services:
  frontend:
    build:
      context: ./app # Path to your React app directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 on host to port 80 in container
    depends_on:
      - backend

  backend:
    build:
      context: ./backend # Path to your Node.js app directory
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map port 5000 on host to port 5000 in container